set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.webhelp\lib\ant-contrib-1.0b3.jar"
set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.highlight\lib\xslthl-2.1.1.jar"
set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\org.dita.odt\lib\odt.jar"
set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\org.dita.pdf2\lib\fo.jar"
set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\org.dita.pdf2.axf\lib\axf.jar"
set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\org.dita.pdf2.xep\lib\xep.jar"
set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\org.dita.wordrtf\lib\wordrtf.jar"
